namespace Mercury.Generators.Architecture;

internal static class ArchitectureTemplates {
    
    #region Attributes

    public const string ProcessorFlagsAttributeText =
        """
        // <auto-generated />
        using System;

        namespace Mercury.Generators;

        /// <summary>
        /// Attribute that marks an enum as being the definition of flags that a 
        /// coprocessor has.
        /// </summary>
        [AttributeUsage(AttributeTargets.Enum, Inherited = false, AllowMultiple = false)]
        public class ProcessorFlagsAttribute : Attribute {
            public ProcessorFlagsAttribute(Mercury.Engine.Common.Architecture architecture) {
            }
            public required int Processor { get; init; }
        }
        """;

    public const string InvalidAttributeText =
        """
        // <auto-generated />
        using System;

        namespace Mercury.Generators;

        /// <summary>
        /// Attribute that marks a field of an enum as not
        /// being a valid architecture value.
        /// </summary>
        [AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
        public class InvalidAttribute : Attribute {
            public InvalidAttribute() {
            }
        }
        """;

    public const string ArchitectureAttributeText =
        """
        // <auto-generated />
        using System;

        namespace Mercury.Generators;

        [AttributeUsage(AttributeTargets.Enum, Inherited = false, AllowMultiple = false)]
        public class ArchitectureAttribute : Attribute {
            public ArchitectureAttribute() {
            }
        }

        """;

    #endregion

    #region Data Definition Structures

    public const string ArchitectureMetadataText =
        """
        // <auto-generated />

        using System;

        namespace Mercury.Engine.Common;

        /// <summary>
        /// A struct to represent metadata about a register.
        /// </summary>
        public record ArchitectureMetadata(Processor[] Processors);
        """;
    
    public const string ProcessorText =
        """
        // <auto-generated />
        using System;

        namespace Mercury.Engine.Common;

        /// <summary>
        /// Represents a processor inside an architecture.
        /// </summary>
        public record Processor(int Number, string Name, RegisterGroup[] Groups, string[] Flags);
        """;

    public const string RegisterGroupText =
        """
        // <auto-generated />
        using System;
        
        namespace Mercury.Engine.Common;
        
        public record RegisterGroup(Type Type, RegisterDefinition[] Registers, string Name);
        """;
    
    public const string RegisterDefinitionText =
        """
        // <auto-generated />

        using System;

        namespace Mercury.Engine.Common;

        /// <summary>
        /// A struct to represent a register inside a processor.
        /// </summary>
        public record RegisterDefinition(int Number, string Name, int BitSize, bool IsGeneralPurpose, Enum Reference);
        """;

    #endregion
    
    public const string ArchitectureManagerText =
        """
        // <auto-generated />

        using System;

        namespace Mercury.Engine.Common;

        /// <summary>
        /// Static class that holds all metadata about the different available architectures.
        /// </summary>
        public static class ArchitectureManager {{
            private static readonly List<Architecture> AvailableArchitectures;
            private static readonly Dictionary<Architecture, ArchitectureMetadata> ArchitectureMetadata = [];
            /// <summary>
            /// Returns a readonly collection of all the currently supported architectures.
            /// </summary>
            public static IReadOnlyList<Architecture> GetAvailableArchitectures() => AvailableArchitectures;
            
            /// <summary>
            /// Returns the metadata of an architecture.
            /// </summary>
            public static ArchitectureMetadata GetArchitectureMetadata(Architecture architecture) {{
                return ArchitectureMetadata[architecture];
            }}
            
            /// <summary>
            /// Static constructor to initialize the available architectures and their metadata.
            /// </summary>
            static ArchitectureManager() {{
                // list with recognized architectures
                AvailableArchitectures = [
        {0}
                ];
                // initialization of metadata for each architecture
        {1}
            }}
           
            #region Initializers 
        {2}
            #endregion
        }}
        """;
    
    public const string RegisterInitializationText =
        """
                            new RegisterDefinition({0}, "{1}", {2}, {3}, {4}),
        """;
    

}