using System;
using System.Collections.Generic;

namespace Mercury.Editor.Models.Compilation;

/// <summary>
/// A structure with information about the result
/// of a compilation process.
/// </summary>
public readonly struct CompilationResult
{
    /// <summary>
    /// A unique identifier for this compilation. If all the
    /// input files are the same, the identifier will be the same.
    /// </summary>
    public Guid Id { get; init; }
    
    /// <summary>
    /// Whether the compilation was successful or not.
    /// </summary>
    public bool IsSuccess { get; init; }

    /// <summary>
    /// The type of error that ocurred if <see cref="IsSuccess"/> is false.
    /// </summary>
    public CompilationError Error { get; init; }
    
    /// <summary>
    /// A list with all the diagnostics generated by the compilation
    /// </summary>
    public List<Diagnostic>? Diagnostics { get; init; }
    
    /// <summary>
    /// An absolute path to the final compiled binary.
    /// </summary>
    public string? OutputPath { get; init; }
}