namespace Mercury.Editor.Models.Compilation;

public enum CompilationError {
    /// <summary>
    /// No error ocurred.
    /// </summary>
    None,
    /// <summary>
    /// An internal logic of the program failed. Debugging is required
    /// by the developer
    /// </summary>
    InternalError,
    /// <summary>
    /// A program to be executed was not found.
    /// </summary>
    ProgramError,
    /// <summary>
    /// The compilation took too long, so it must have failed.
    /// </summary>
    TimeoutError,
    /// <summary>
    /// The compiler failed.
    /// </summary>
    CompilationError,
    /// <summary>
    /// An error ocurred when linking the final executable
    /// </summary>
    LinkError,
    /// <summary>
    /// The program wasn't able to read the ELF file
    /// generated by the compiler
    /// </summary>
    ElfError
}