namespace Mercury.Generators.Registers;

internal static class RegisterInfoTemplates {
    #region Attributes

    public const string RegisterAttributeText =
        """
        // <auto-generated />
        namespace Mercury.Generators {

            [System.AttributeUsage(System.AttributeTargets.Field)]
            public class RegisterAttribute : System.Attribute {

                public RegisterAttribute(int number, string name, int size, bool isGpr) {
                    
                }

                public RegisterAttribute(string name, int size, bool isGpr) {
                    
                }
            }
        }
        """;

    public const string RegisterGroupAttribute =
        """
        // <auto-generated />
        #nullable enable
        namespace Mercury.Generators {

            [System.AttributeUsage(System.AttributeTargets.Enum)]
            public class RegisterGroupDefinitionAttribute : System.Attribute {
                
                /// <summary>
                /// The index of the processor that this group belongs to.
                /// </summary>
                public required int Processor { get; init; }
                
                /// <summary>
                /// The name of the group. May be a translation key to be used in the frontend application.
                /// </summary>
                public required string Name { get; init; }
                
                /// <summary>
                /// The user-friendly name of the processor that this group belongs to. If more than one group
                /// of a processor defines this value, the resulting name is going to be one of them.
                /// </summary>
                public string? ProcessorName { get; init; } = null;
            
                public RegisterGroupDefinitionAttribute(Mercury.Engine.Common.Architecture architecture) {
                    
                }
            }
        }
        """;

    #endregion

    #region Formats

    public const string SwitchCaseFormat =
        """
                        case {0}:
                            return {1};
        """;

    public const string SharedIfRegisterFormat =
        """
                    if(typeof(TRegister) == typeof({0})){{
                        return (TRegister?)(object?)Get{1}FromNumber(number);
                    }}
        """;

    public const string SharedIfNumberFormat =
        """
                    if(reg.GetType() == typeof({0})) {{
                        return GetRegisterNumber(({1})reg);
                    }}
        """;

    public const string SharedIfNameFormat =
        """
                    if(reg.GetType() == typeof({0})) {{
                        return GetRegisterName(({1})reg);
                    }}
        """;

    public const string SharedIfInvNameFormat =
        """
                    if(type == typeof({0})) {{
                        return (Enum?)Get{1}FromName(name);
                    }}
        """;

    public const string SharedIfGetFromNumberFormat =
        """
                    if(type == typeof({0})) {{
                        return (Enum?)Get{1}FromNumber(number);
                    }}
        """;

    public const string SharedIfCountFormat =
        """
                    if(typeof(TRegister) == typeof({0})){{
                        return Get{1}Count();
                    }}
        """;

    public const string ProviderCaseFormat =
        """
                    {0}.{1} => new {2}RegisterHelper(),
        """;

    #endregion

    #region Classes

    public const string ImplementationRegisterSetFormat =
        """
        // <auto-generated />
        namespace Mercury.Engine.Common {{
            public partial class {0}RegisterHelper {{
                public static int? GetRegisterNumber({1} reg) {{
                    switch (reg) {{
        {2}
                    }}
                    return null;
                }}
                
                public static string GetRegisterName({3} reg) {{
                    switch(reg) {{
        {4}
                    }}
                    return null;
                }}
                
                public static int Get{5}Count(){{
                    return {6};
                }}
                
                public static {7}? Get{8}FromNumber(int number){{
                    switch(number) {{
        {9}
                    }}
                    return null;
                }}
                
                public static {10}? Get{11}FromName(string name){{
                    switch(name){{
        {12}
                    }}
                    return null;
                }}
            }}
        }}
        """;

    public const string SharedImplementationFormat =
        """
        // <auto-generated />
        #nullable enable
        namespace Mercury.Engine.Common {{
            public partial class {0}RegisterHelper : IRegisterHelper {{
                public static TRegister? GetRegister<TRegister>(int number) where TRegister : struct, Enum {{
        {1}
                    return null;
                }}
                
                public static int GetCount<TRegister>() where TRegister : struct, Enum {{
        {2}
                    return 0;
                }}
                
                public TRegister? GetRegisterX<TRegister>(int number) where TRegister : struct, Enum {{
                    return GetRegister<TRegister>(number);
                }}
                
                public static int? GetRegisterNumber(Enum reg) {{
        {3}
                    return null;
                }}
                
                public int? GetRegisterNumberX(Enum reg) {{
                    return GetRegisterNumber(reg);
                }}
                
                public static string GetRegisterName(Enum reg) {{
        {4}
                    throw new System.ArgumentOutOfRangeException(nameof(reg));
                }}
                
                public string GetRegisterNameX(Enum reg) {{
                    return GetRegisterName(reg);
                }}
                
                public static Enum? GetRegisterFromName(string name, Type type){{
        {5}
                    throw new System.ArgumentOutOfRangeException(nameof(name));
                }}
                
                public Enum? GetRegisterFromNameX(string name, Type type){{
                    return GetRegisterFromName(name, type);
                }}
                
                public static Enum? GetRegisterFromNumber(int number, Type type) {{         
        {6}
                    throw new System.ArgumentOutOfRangeException(nameof(type));
                }}
                
                public Enum? GetRegisterFromNumberX(int number, Type type) {{
                    return GetRegisterFromNumber(number, type);
                }}
            }}
        }}
        """;

    public const string ProviderFormat =
        """
        // <auto-generated />
        namespace Mercury.Engine.Common;

        public static class RegisterHelperProvider
        {{
            public static IRegisterHelper ProvideHelper({0} architecture)
            {{
                return architecture switch
                {{
        {1}
                    _ => throw new NotImplementedException($"No register helper implemented for architecture {{architecture}}")
                }};
            }}
        }}
        """;

    #endregion
}