using System;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Mercury.Generators;

[Generator]
public class BuildTimeGenerator : IIncrementalGenerator
{
    private const string Template = 
        """
        // <auto-generated/>
        using System;
        
        namespace Mercury.Editor;
        
        public static class BuildInfo {
            public static readonly DateTime BuildTime = new DateTime({ticks}, DateTimeKind.Utc);
        }
        """;
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            string code = Template.Replace("{ticks}", DateTime.UtcNow.Ticks.ToString());
            ctx.AddSource("BuildInfo.g.cs", SourceText.From(code, Encoding.UTF8));
        });
    }
}