namespace Mercury.Generators.Instruction;

internal static class InstructionTemplates {

    public const string InstructionAttribute =
        """
        // <auto-generated/>

        using System;

        namespace Mercury.Engine.Generators.Instruction;

        /// <summary>
        /// Marks that a class is an instruction and should be analyzed by Mercury and have code generated for it.
        /// </summary>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = true)]
        public class InstructionAttribute : Attribute { }
        """;

    public const string FieldAttribute =
        """
        // <auto-generated/>

        using System;

        namespace Mercury.Engine.Generators.Instruction;

        /// <summary>
        /// Marks that a field or property must be populated with data from the binary instruction on decoding.
        /// </summary>
        [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property)]
        public class FieldAttribute : Attribute {
            /// <summary>
            /// Creates the attribute that marks the field.
            /// </summary>
            /// <param name="bitStart">The inclusive index of the first bit</param>
            /// <param name="bitEnd">The inclusive index of the last bit</param>
            public FieldAttribute(int bitStart, int bitEnd) { }
        }
        """;

    public const string PartialInstruction =
        """
        // <auto-generated/>
        
        namespace {0};
        
        public partial class {1} {{
            public void FromInt(uint value) {{
        {2}
            }}
            
            public uint ConvertToInt() {{
        {3} 
            }}
        }}
        """;

    public const string PartialInstructionFieldExtract =
        """
                {0} = ({1})((value >> {2}) & {3});
        """;
    
    public const string FormatExactAttributeText =
            """
            // <auto-generated />
            using System;
            
            namespace Mercury.Engine.Generators.Instruction;
            
            /// <summary>
            /// Specifies a constraint on the bit values of an instruction.
            /// </summary>
            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = true)]
            public class FormatExactAttribute : Attribute {
            
                /// <summary>
                /// Specifies that a bit span of the instruction must match any of the provided values.
                /// </summary>
                public FormatExactAttribute(int bitStart, int bitEnd, int[] values) {
                    
                }
                
                /// <summary>
                /// Specifies that a bit span of the instruction must match the provided value.
                /// </summary>
                public FormatExactAttribute(int bitStart, int bitEnd, int value) {
                    
                }
            }
            """;

    public const string FormatDifferentAttribute =
        """
        // <auto-generated />
        using System;

        namespace Mercury.Engine.Generators.Instruction;

        /// <summary>
        /// Specifies a constraint on the bit values of an instruction. Demands
        /// that a span of the instruction must not match a value. 
        /// </summary>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = true)]
        public class FormatDifferentAttribute : Attribute {

            /// <summary>
            /// Specifies that a bit span of the instruction must not match any of the provided values.
            /// </summary>
            public FormatDifferentAttribute(int bitStart, int bitEnd, int[] values) {
                
            }
            
            /// <summary>
            /// Specifies that a bit span of the instruction must not match the provided value.
            /// </summary>
            public FormatDifferentAttribute(int bitStart, int bitEnd, int value) {
                
            }
        }
        """;
            
        public const string DisassemblerFormat =
            """
            // <auto-generated />
            #nullable enable
            using System;
            using System.Runtime.CompilerServices;

            namespace {0};

            /// <summary>
            /// Simple wrapper class for the <see cref="Disassemble"/> method.
            /// </summary>
            /// <remarks>{1} instructions registered.</remarks>
            public static class Disassembler {{
                private static global::Mercury.Engine.Common.IInstruction? GetType(uint instruction, InstructionPool pool) {{
            {2}
                    return null;
                }}
                
                public static global::Mercury.Engine.Common.IInstruction? Disassemble(uint instruction, InstructionPool pool) {{
                    global::Mercury.Engine.Common.IInstruction? type = GetType(instruction, pool);
                    if (type is null) {{
                        return null;
                    }}
                    type.FromInt(instruction);
                    return type;
                }}
            }}
            """;

        public const string PoolFormat =
            """
            // <auto-generated />
            #nullable enable
            using System;
            
            namespace {0};
            
            /// <summary>
            /// A class that has all available instructions in its fields. Used to avoid allocations
            /// of the same instructions. 
            /// </summary>
            public class InstructionPool {{
            {1}
            }}
            """;
}